name: Build (Pull Request)

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: Create local.properties
        run: echo "QIITA_CLIENT_ID=${{ secrets.QIITA_CLIENT_ID }}\nQIITA_CLIENT_SECRET=${{ QIITA_CLIENT_SECRET }}" > local.properties

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Check
        run: |
          ./gradlew lintDebug

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install bundler
        run: |
          GEM_BUNDLER_VERSION=$(grep -A1 -E -i -w '(BUNDLED WITH){1,1}' .ci/Gemfile.lock | grep -E -i -w "[0-9\.]{1,}" | xargs)
          gem install bundler -v=$GEM_BUNDLER_VERSION --force

      - name: Run danger for static analysis
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle install --gemfile=.ci/Gemfile
          bundle exec --gemfile=.ci/Gemfile danger --dangerfile=".ci/danger/static_analysis.danger"

      - name: Upload build outputs
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: app/build/outputs/apk/**/*.apk
