name: Build (Pull Request)

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install bundler
        run: |
          GEM_BUNDLER_VERSION=$(grep -A1 -E -i -w '(BUNDLED WITH){1,1}' .ci/Gemfile.lock | grep -E -i -w "[0-9\.]{1,}" | xargs)
          gem install bundler -v=$GEM_BUNDLER_VERSION --force

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: Create local.properties
        env:
          QIITA_CLIENT_ID: ${{ secrets.QIITA_CLIENT_ID }}
          QIITA_CLIENT_SECRET: ${{ secrets.QIITA_CLIENT_SECRET }}
        run: |
          echo "QIITA_CLIENT_ID=$QIITA_CLIENT_ID" >> local.properties
          echo "QIITA_CLIENT_SECRET=$QIITA_CLIENT_SECRET" >> local.properties

      - name: Build and check
        run: |
          ./gradlew spotlessCheck
          ./gradlew assembleDebug
          ./gradlew lintDebug
          ./gradlew testDebug

      - name: Run danger for static analysis
        if: ${{ always() }}
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle install --gemfile=.ci/Gemfile
          bundle exec --gemfile=.ci/Gemfile danger --dangerfile=".ci/danger/static_analysis.danger"

      - name: Upload build outputs
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: app/build/outputs/apk/**/*.apk
